### PR TITLE
Add xcode 10 compatibility

### PR DESCRIPTION
**Pull request by 4brunu**
Hello, Bridgecraft is not working with Xcode 10, so here is a PR to make it compatible.

Basically the problem is that the new build system, the default one in Xcode 10, doesn't support `-dry-run` yet, so in order to Bridgecraft to work, it must explicitly use the legacy build system.

Once the new build system supports `-dry-run`, the flag `-UseModernBuildSystem=0` can be removed.

I also replaced `-n` with `-dry-run`, because the error that was outputted was `error: -dry-run is not yet supported in the new build system`, but I couldn't find that option anywhere, until after a lot of trial error, I discovered that `-n` and `-dry-run` are the same, maybe `-n` it's just the abbreviation, so I made it explicitly.

I added pin versions to Carthage, to make sure that Carthage and Swift Package Manager dependencies versions match.

NOTE: This is not related itself with the PR, but there are some dependencies that are not it compatible with Swift 4.2, and Xcode 10 can't build Bridgecraft, so in order to create the next release, you will need to use Xcode 9. This also applies when updating Carthage.

If you have any question please let me know.

### CODE REVIEW

**Comment by lvsti** [comment]
Hey, thanks for the fixes, I appreciate it! I didn't manage to compile the project due to some errors in XcodeEditor so I unearthed an old branch of mine where I replaced it with [XcodeEdit](https://github.com/tomlokhorst/XcodeEdit) which, unlike XcodeEditor, is still being developed.

**Comment by lvsti** [comment]
well it still doesn't compile on my machine with the new toolchain because Carthage cannot build the Yams dependency... 😠 

```fatal error: Unexpected Swift version: file /tmp/swiftlint-20170407-45056-wip7rd/Source/SwiftLintFramework/Models/SwiftVersion.swift, line 38```

**Comment by lvsti** [comment]
nevermind, updating swiftlint solved it

**Comment by 4brunu** [comment]
Thanks 👍

**Pull request merged**
